(define (foo a b c)
  (define (sum-square x y)
    (+ (* x x) (* y y)))
  (if (> a b)
    (if (> b c)
      (sum-square a b)
      (sum-square a c))
    (if (> a c)
      (sum-square b a)
      (sum-square b c))))

(foo 1 2 3)
(foo 3 1 2)
(foo 2 3 1)
